import { Box, Button, Grid, Typography } from '@mui/material';
import { Inter } from 'next/font/google';
import Head from 'next/head';

import Brands from '@/components/Brands';
import { homeData } from '@/data/homeData';
import Image from 'next/image';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>JustYol</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          maxWidth: '1500px',
          marginInline: 'auto',
          padding: '1rem',
          paddingY: {
            xs: 4,
            sm: 8,
            md: 10,
            lg: 10,
            xl: 10,
          },
          display: 'flex',
          flexDirection: 'column',
          gap: 8,
        }}
      >
        <Box
          sx={{
            display: 'flex',
            flexDirection: 'column',
            gap: 4,
          }}
        >
          <Typography
            component="h2"
            variant="h2"
            sx={{
              fontSize: {
                xs: 15,
                sm: 20,
                md: 30,
                lg: 40,
                xl: 40,
              },
              fontWeight: 600,
            }}
          >
            ! جاست يول أناقة تفوق الحدود، وجهتك المثالية للموضة
          </Typography>
          <Typography
            sx={{
              fontSize: {
                xs: 10,
                sm: 10,
                md: 15,
                lg: 20,
                xl: 20,
              },
            }}
          >
            اختيارك المفضل للتسوق اونلاين في العديد من دول العالم ودول الخليج ،
            جست يول توفر مجموعة ملابس وأحذية وإكسسوارات ومستحضرات تجميل ولوازم
            المنزل وهدايا للجميع. مجموعتنا تلبي احتياجات الرجال والنساء والأطفال
            ، مع تشكيلة واسعة من العلامات التجارية من نايكي وجنجر واديداس و
            غيرها الكثير. نحن نقدم تجربة تسوق سهلة تتضمن الدفع لاحقا والتوصيل
            السريع وخدمة عملاء ذات مستوى عالمي ومجموعة منتجات جديدة يوميا
          </Typography>
        </Box>
        <Grid
          spacing={2}
          sx={{
            display: 'flex',
            flexDirection: {
              xs: 'column',
              sm: 'column',
              md: 'row',
              lg: 'row',
              xl: 'row',
            },
            alignItems: 'center',
            gap: 5,
          }}
        >
          {homeData.map((item, index) => (
            <Grid
              item
              xs={12}
              sm={6}
              md={6}
              lg={3}
              xl={3}
              key={index}
              sx={{
                position: 'relative',
                overflow: 'hidden',
                '&:hover .text-container': {
                  visibility: 'visible',
                  opacity: 1,
                },
              }}
            >
              <Box>
                <Box
                  sx={{
                    width: {
                      xs: '50%',
                      sm: '50%',
                      md: '100%',
                      lg: '100%',
                      xl: '100%',
                    },
                    margin: '0 auto',
                  }}
                >
                  <Image
                    src={item.img}
                    alt="image"
                    // layout="responsive"
                    style={{
                      width: '100%',
                      height: '100%',
                      objectFit: 'contain',
                    }}
                  />
                </Box>
                <Box
                  sx={{
                    position: 'absolute',
                    bottom: 0,
                    left: 0,
                    right: 0,
                    background:
                      'linear-gradient(to top, rgba(0, 0, 0, 1) 40%, rgba(0, 0, 0, 0) 100%)',
                    padding: 1,
                    textAlign: 'center',
                    visibility: 'visible',
                    opacity: 1,
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    gap: 1,
                    transition: 'background-color 0.3s',
                  }}
                >
                  <Typography
                    variant="subtitle1"
                    sx={{ color: '#ffffff', fontSize: '32px', fontWeight: 600 }}
                  >
                    {item.topText}
                  </Typography>
                  <Typography
                    variant="subtitle1"
                    sx={{
                      color: '#ffffff',
                      fontSize: '14px',
                      visibility: 'hidden',
                      opacity: 0,
                      transition: 'visibility 0s, opacity 0.3s linear',
                    }}
                    className="text-container"
                  >
                    {item.middleText}
                  </Typography>
                  <Button
                    variant="contained"
                    sx={{
                      backgroundColor: '#ffffff',
                      width: 100,
                      fontSize: 15,
                      color: '#000000',
                      '&:hover': {
                        backgroundColor: '#FF6666',
                        color: '#ffffff',
                      },
                    }}
                  >
                    تسوق الآن
                  </Button>
                </Box>
              </Box>
            </Grid>
          ))}
        </Grid>
        <Brands />
      </Box>
    </>
  );
}
